version: '3'  # Specify the Docker Compose version

services:
  web:  # This is the name of your service
    build:
      context: .
      dockerfile: Dockerfile  # Corrected the Dockerfile name
    ports:
      - "3000:3000"  # Replace your_host_port and container_port with the appropriate values
    volumes:
      - .:/app  # Mount the current directory to /app in the container
#      - /app/node_modules  # Mount the node_modules directory as a volume to avoid overwriting it with the host's node_modules
